//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskDetail
    {
        public int Id { get; set; }
        public string TaskDescription { get; set; }
        public System.DateTime TodayDate { get; set; }
        public System.DateTime DeadLine { get; set; }
        public System.DateTime CompletedOn { get; set; }
        public string Remark { get; set; }
        public int AssignId { get; set; }
        public int DepartmentId { get; set; }
        public int PriorityId { get; set; }
        public int StatusId { get; set; }
        public int TaskTypeId { get; set; }
    
        public virtual Assign Assign { get; set; }
        public virtual Department Department { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual Status Status { get; set; }
        public virtual TaskType TaskType { get; set; }
    }
}
